window.__appReady=true;
const SUPABASE_URL='https://kpzcvreqjkgevzmlipjs.supabase.co';
const SUPABASE_KEY='sb_publishable_PgFcb8Fu86xyZ1Fiu1ftEQ_664m7EdB';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let sb=null,orders=[],prepOrders=[],products=[],days=[],exceptions=[],chats=[],clients=[],activeClient=null;
try {
  if(!window.supabase || typeof window.supabase.createClient!=='function') throw new Error('Biblioteca Supabase indisponível.');
  sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});
  window.__supabaseClientReady=true;
} catch(e) {
  window.__appInitError=e?.message||String(e);
  const box=document.getElementById('loginError'); if(box) box.textContent='Falha ao iniciar Supabase: '+window.__appInitError;
}

const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const fmt=d=>d?new Date(d+'T12:00:00').toLocaleDateString('pt-BR'):'';const toast=t=>{let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)};const err=e=>toast(e?.message||String(e));
async function getOrCreateSession(){let r=await sb.auth.getSession();if(r.error)throw r.error;let session=r.data.session;if(!session){let a=await sb.auth.signInAnonymously();if(a.error)throw a.error;session=a.data.session}if(!session)throw new Error('Não foi possível criar a sessão do gerente. Verifique se Anonymous Sign-Ins está ativado no Supabase.');return session}
async function ensureAuth(){try{await getOrCreateSession();let g=await sb.rpc('sou_gerente');if(g.error)throw g.error;if(g.data){showApp();await loadAll()}else{$('#login').classList.remove('hidden')}}catch(e){$('#loginError').textContent='Erro de conexão: '+(e?.message||String(e));$('#login').classList.remove('hidden')}}
window.managerLogin=async()=>{const btn=$('#loginBtn'),box=$('#loginError'),senha=$('#managerPassword').value;box.textContent='';if(!senha){box.textContent='Digite a senha do gerente.';return}btn.disabled=true;btn.textContent='Entrando…';try{await getOrCreateSession();let r=await sb.rpc('ativar_gerente',{p_senha:senha,p_nome_computador:$('#deviceName').value.trim()||navigator.platform||'Computador'});if(r.error)throw r.error;let check=await sb.rpc('sou_gerente');if(check.error)throw check.error;if(!check.data)throw new Error('A sessão foi criada, mas este computador não foi autorizado.');showApp();await loadAll()}catch(e){box.textContent=e?.message||String(e)}finally{btn.disabled=false;btn.textContent='Entrar'}};
$('#loginBtn').addEventListener('click',e=>{e.preventDefault();window.managerLogin()});$('#managerPassword').addEventListener('keydown',e=>{if(e.key==='Enter')window.managerLogin()});
window.addEventListener('unhandledrejection',e=>{let box=$('#loginError');if(box&&!$('#login').classList.contains('hidden'))box.textContent='Erro: '+(e.reason?.message||String(e.reason||'Falha inesperada.'))});
function showApp(){$('#login').classList.add('hidden');$('#app').classList.remove('hidden')}
$$('nav button[data-page]').forEach(b=>b.onclick=()=>{let p=b.dataset.page;$$('nav button').forEach(x=>x.classList.toggle('active',x===b));$$('.page').forEach(x=>x.classList.toggle('active',x.id===p));let map={orders:['Pedidos aguardando confirmação','Confirme ou cancele os pedidos enviados'],preparation:['Pedidos em preparação','Pedidos confirmados por data de entrega'],chat:['Chat','Conversas com clientes'],clients:['Clientes','Cadastre e gerencie o acesso dos clientes'],products:['Produtos','Catálogo e estoque'],delivery:['Entregas','Dias, cortes e exceções'],settings:['Configurações','Segurança do painel']};$('#pageTitle').textContent=map[p][0];$('#pageSub').textContent=map[p][1];if(p==='preparation')loadPreparation();if(p==='chat')loadChats();if(p==='clients')loadClients();if(p==='products')loadProducts();if(p==='delivery')loadDelivery();if(p==='settings')loadDevices()});
async function loadAll(){await Promise.all([loadOrders(),loadPreparation(),loadProducts(),loadDelivery(),loadChats(),loadClients(),loadDevices()])}$('#refreshBtn').onclick=loadAll;$('#orderFilter').onchange=loadOrders;
async function loadOrders(){let {data,error}=await sb.rpc('gerente_listar_pedidos',{p_filtro:'pending'});if(error)return err(error);orders=(data||[]).filter(o=>o.status==='enviado');$('#statWaiting').textContent=orders.length;let all=await sb.rpc('gerente_listar_pedidos',{p_filtro:'confirmado'});let confirmed=all.data||[];$('#statConfirmed').textContent=confirmed.filter(o=>String(o.criado_em).slice(0,10)===new Date().toISOString().slice(0,10)).length;$('#orderBadge').textContent=orders.length||'';$('#ordersList').innerHTML=orders.map(o=>`<div class="order-card"><div><h3>Pedido #${esc(o.numero)} — ${esc(o.cliente)}</h3><span class="status enviado">Aguardando confirmação</span><p><b>Entrega:</b> ${fmt(o.data_entrega)} · <b>Enviado por:</b> ${esc(o.enviado_por)}</p><p>${(o.itens||[]).map(i=>`${esc(i.quantidade)} ${esc(i.unidade)} ${esc(i.nome)}`).join(' · ')}</p></div><div class="actions"><button class="primary" onclick="orderAction('confirmar',${o.id})">Confirmar</button><button class="danger" onclick="orderAction('cancelar',${o.id})">Cancelar</button><button class="soft" onclick="openChat(${o.cliente_id})">Chat</button></div></div>`).join('')||'<div class="panel">Nenhum pedido aguardando confirmação.</div>'}
window.orderAction=async(a,id)=>{if(!confirm(a==='cancelar'?'Cancelar este pedido?':'Confirmar este pedido e enviar para preparação?'))return;let {error}=await sb.rpc(`gerente_${a}_pedido`,{p_id:id});if(error)return err(error);toast(a==='confirmar'?'Pedido enviado para preparação':'Pedido cancelado');await Promise.all([loadOrders(),loadPreparation()])};
async function loadPreparation(){let {data,error}=await sb.rpc('gerente_listar_pedidos',{p_filtro:'confirmado'});if(error)return err(error);prepOrders=data||[];let dates=[...new Set(prepOrders.map(o=>o.data_entrega).filter(Boolean))].sort();let sel=$('#prepDate'),old=sel.value;sel.innerHTML=dates.map(d=>`<option value="${esc(d)}">${fmt(d)}</option>`).join('')||'<option value="">Nenhum pedido confirmado</option>';if(dates.includes(old))sel.value=old;else if(dates.length)sel.value=dates[0];renderPrepDateCards(dates);renderPreparation()}
function renderPrepDateCards(dates){let box=$('#prepDateCards');if(!box)return;box.innerHTML=dates.map(d=>{let dt=new Date(d+'T12:00:00');return `<button class="prep-date ${$('#prepDate').value===d?'active':''}" onclick="selectPrepDate('${d}')"><strong>${String(dt.getDate()).padStart(2,'0')}</strong><small>${dt.toLocaleDateString('pt-BR',{weekday:'short',month:'short'})}</small></button>`}).join('')||'<span>Nenhuma data com pedidos confirmados.</span>'}
window.selectPrepDate=d=>{$('#prepDate').value=d;renderPrepDateCards([...new Set(prepOrders.map(o=>o.data_entrega).filter(Boolean))].sort());renderPreparation()};
function renderPreparation(){let date=$('#prepDate').value,list=prepOrders.filter(o=>o.data_entrega===date);let totals={};for(let o of list)for(let i of(o.itens||[])){let k=i.nome+'|'+i.unidade;if(!totals[k])totals[k]={nome:i.nome,unidade:i.unidade,q:0};totals[k].q+=Number(i.quantidade)||0}$('#prepSummary').innerHTML=date?`<h3>Entrega ${fmt(date)}</h3><p><b>${list.length}</b> pedido(s) confirmado(s) · <b>${Object.keys(totals).length}</b> produto(s) diferentes</p>`:'<p>Nenhum pedido confirmado para preparação.</p>';$('#prepOrders').innerHTML=list.map(o=>`<div class="prep-card"><h3>${esc(o.cliente)}</h3><p>Pedido #${esc(o.numero)} · Enviado por ${esc(o.enviado_por)}</p><ul>${(o.itens||[]).map(i=>`<li><b>${esc(i.quantidade)} ${esc(i.unidade)}</b> — ${esc(i.nome)}</li>`).join('')}</ul></div>`).join('')}
$('#prepDate').onchange=()=>{renderPrepDateCards([...new Set(prepOrders.map(o=>o.data_entrega).filter(Boolean))].sort());renderPreparation()};
$('#printPrep').onclick=()=>{let date=$('#prepDate').value,list=prepOrders.filter(o=>o.data_entrega===date);if(!date||!list.length)return toast('Não há pedidos nesta data.');let totals={};for(let o of list)for(let i of(o.itens||[])){let k=i.nome+'|'+i.unidade;if(!totals[k])totals[k]={nome:i.nome,unidade:i.unidade,q:0};totals[k].q+=Number(i.quantidade)||0}let w=window.open('','_blank');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Folha de preparação ${fmt(date)}</title><style>@page{size:A4;margin:10mm}body{font-family:Arial,sans-serif;color:#111;margin:0}h1{font-size:18px;margin:0 0 12px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.card{border:1px solid #777;border-radius:6px;padding:7px;break-inside:avoid;font-size:10px}.card h2{font-size:12px;margin:0 0 4px}.card ul{margin:4px 0;padding-left:15px}.totals{page-break-before:auto;margin-top:14px;border-top:2px solid #111;padding-top:8px}.totals h2{font-size:14px}.totals ul{columns:2;font-size:11px}@media print{button{display:none}}</style></head><body><h1>Folha de preparação — ${fmt(date)}</h1><div class="grid">${list.map(o=>`<div class="card"><h2>${esc(o.cliente)}</h2><div>Pedido #${esc(o.numero)}</div><ul>${(o.itens||[]).map(i=>`<li>${esc(i.quantidade)} ${esc(i.unidade)} — ${esc(i.nome)}</li>`).join('')}</ul></div>`).join('')}</div><div class="totals"><h2>Total por produto</h2><ul>${Object.values(totals).sort((a,b)=>a.nome.localeCompare(b.nome)).map(t=>`<li><b>${esc(t.q)} ${esc(t.unidade)}</b> — ${esc(t.nome)}</li>`).join('')}</ul></div><script>window.onload=()=>{window.print()}<\/script></body></html>`);w.document.close()};
async function loadChats(){let {data,error}=await sb.rpc('gerente_listar_chats_v17');if(error)return err(error);chats=data||[];renderChats();updateChatBadge()}
function updateChatBadge(){let n=chats.reduce((a,c)=>a+Number(c.nao_lidas||0),0),b=$('#chatBadge');b.textContent=n||'';b.classList.toggle('has',n>0)}
function renderChats(){let q=($('#chatSearch').value||'').toLowerCase();$('#chatClients').innerHTML=chats.filter(c=>c.cliente.toLowerCase().includes(q)).map(c=>`<div class="chat-person ${activeClient===c.cliente_id?'active':''} ${Number(c.nao_lidas)>0?'unread-row':''}" onclick="openChat(${c.cliente_id})"><b>${esc(c.cliente)}</b><small>${esc(c.ultima_mensagem||'')}</small>${Number(c.nao_lidas)>0?`<span class="unread">${c.nao_lidas}</span>`:''}</div>`).join('')||'<div class="chat-person">Nenhuma conversa.</div>'}$('#chatSearch').oninput=renderChats;
window.openChat=async id=>{activeClient=id;$$('nav button[data-page]').find(b=>b.dataset.page==='chat').click();let c=chats.find(x=>x.cliente_id===id);$('#chatHead').textContent=c?.cliente||'Cliente';renderChats();await loadMessages();await loadChats()};
function managerChecks(m){if(m.remetente!=='gerente')return '';return `<span class="msg-check ${m.lida_cliente?'read':''}" title="${m.lida_cliente?'Lida pelo cliente':'Entregue'}"><span>✓</span>${m.lida_cliente?'<span class="tick2">✓</span>':''}</span>`}
async function loadMessages(){if(!activeClient)return;let {data,error}=await sb.rpc('gerente_mensagens',{p_cliente_id:activeClient});if(error)return err(error);$('#managerMessages').innerHTML=(data||[]).map(m=>`<div class="bubble ${m.remetente==='gerente'?'me':''}">${esc(m.mensagem)}<div class="meta"><small>${new Date(m.criado_em).toLocaleString('pt-BR')}</small>${managerChecks(m)}</div></div>`).join('');$('#managerMessages').scrollTop=$('#managerMessages').scrollHeight}
$('#chatInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#chatForm').requestSubmit()}});
$('#chatForm').onsubmit=async e=>{e.preventDefault();let t=$('#chatInput').value.trim();if(!t||!activeClient)return;let {error}=await sb.rpc('gerente_enviar_mensagem',{p_cliente_id:activeClient,p_mensagem:t,p_pedido_id:null});if(error)return err(error);$('#chatInput').value='';await loadMessages();await loadChats()};

async function loadClients(){let {data,error}=await sb.rpc('gerente_listar_clientes_v17');if(error)return err(error);clients=data||[];$('#clientsList').innerHTML=clients.map(c=>`<div class="client-card"><h3>${esc(c.nome)}</h3><p class="phone">${esc(c.telefone)}</p><p>${c.ativo?'Acesso ativo':'Acesso desativado'}</p></div>`).join('')||'<div class="panel">Nenhum cliente cadastrado.</div>'}
$('#newClientBtn').onclick=()=>{$('#modalBody').innerHTML=`<h2>Novo cliente</h2><p>Cadastre o nome, WhatsApp e a senha de acesso ao aplicativo.</p><div class="form-grid"><label class="wide">Nome do cliente<input id="cName" autocomplete="off"></label><label>WhatsApp<input id="cPhone" inputmode="tel" placeholder="31912345678"></label><label>Senha de acesso<input id="cPass" type="password" minlength="4" placeholder="Mínimo 4 caracteres"></label></div><div class="modal-actions"><button class="soft" onclick="closeModal()">Cancelar</button><button class="primary" onclick="saveClient()">Cadastrar cliente</button></div>`;$('#modal').classList.remove('hidden')};
window.saveClient=async()=>{let nome=$('#cName').value.trim(),telefone=$('#cPhone').value.trim(),senha=$('#cPass').value;if(!nome||!telefone||senha.length<4)return toast('Preencha nome, WhatsApp e senha.');let {error}=await sb.rpc('gerente_cadastrar_cliente_v17',{p_nome:nome,p_telefone:telefone,p_codigo:senha});if(error)return err(error);closeModal();toast('Cliente cadastrado');await loadClients()};
async function loadProducts(){let {data,error}=await sb.rpc('gerente_listar_produtos');if(error)return;products=data||[];$('#productsList').innerHTML=products.map(p=>`<div class="product-card"><img src="${esc(p.imagem_url||'assets/logo.png')}" onerror="this.src='assets/logo.png'"><div class="body"><h3>${esc(p.nome)}</h3><p>${esc(p.codigo||'Sem código')} · ${esc(p.unidade)}</p><p><b>Estoque:</b> ${esc(p.quantidade_disponivel)}</p><p>${p.ativo?'Disponível':'Indisponível'}</p><button class="soft" onclick="editProduct(${p.id})">Editar</button></div></div>`).join('')}
$('#newProductBtn').onclick=()=>productModal(null);window.editProduct=id=>productModal(products.find(p=>p.id===id));
function productModal(p){$('#modalBody').innerHTML=`<h2>${p?'Editar':'Novo'} produto</h2><div class="form-grid"><label>Código<input id="pCode" value="${esc(p?.codigo||'')}"></label><label>Nome<input id="pName" value="${esc(p?.nome||'')}"></label><label>Unidade<select id="pUnit">${['UN','KG','DZ','g'].map(u=>`<option ${p?.unidade===u?'selected':''}>${u}</option>`).join('')}</select></label><label>Estoque<input id="pStock" type="number" step="0.001" min="0" value="${p?.quantidade_disponivel??0}"></label><label class="wide">Descrição<textarea id="pDesc">${esc(p?.descricao||'')}</textarea></label><label class="wide">Imagem<input id="pFile" type="file" accept="image/png,image/jpeg,image/webp"></label><div class="wide"><img id="pPreview" class="preview" src="${esc(p?.imagem_url||'assets/logo.png')}"></div><label class="check wide"><input id="pActive" type="checkbox" ${p?.ativo!==false?'checked':''}> Produto disponível</label></div><div class="modal-actions"><button class="soft" onclick="closeModal()">Cancelar</button><button class="primary" id="saveProduct">Salvar produto</button></div>`;$('#modal').classList.remove('hidden');$('#pFile').onchange=()=>{let f=$('#pFile').files[0];if(f)$('#pPreview').src=URL.createObjectURL(f)};$('#saveProduct').onclick=()=>saveProduct(p?.id||null,p?.imagem_url||null)}
async function saveProduct(id,current){try{let image=current,f=$('#pFile').files[0];if(f){let ext=(f.name.split('.').pop()||'jpg').toLowerCase(),path=`${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`;let up=await sb.storage.from('produtos').upload(path,f,{upsert:false});if(up.error)throw up.error;image=sb.storage.from('produtos').getPublicUrl(path).data.publicUrl}let {error}=await sb.rpc('gerente_salvar_produto',{p_id:id,p_codigo:$('#pCode').value,p_nome:$('#pName').value,p_descricao:$('#pDesc').value,p_unidade:$('#pUnit').value,p_estoque:Number($('#pStock').value||0),p_imagem:image,p_ativo:$('#pActive').checked});if(error)throw error;closeModal();toast('Produto salvo');await loadProducts()}catch(e){err(e)}}
window.closeModal=()=>$('#modal').classList.add('hidden');$('#closeModal').onclick=closeModal;
const dayNames=['Domingo','Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira','Sábado'];async function loadDelivery(){let a=await sb.rpc('gerente_dias_entrega'),b=await sb.rpc('gerente_excecoes_entrega');if(a.error||b.error)return;days=a.data||[];exceptions=b.data||[];$('#deliveryDays').innerHTML=dayNames.map((n,i)=>{let d=days.find(x=>x.dia_semana===i)||{ativo:false,horario_corte:'10:00:00',dias_antes_preparacao:1};return `<div class="day-row"><label class="check"><input id="day${i}" type="checkbox" ${d.ativo?'checked':''}> ${n}</label><input id="cut${i}" type="time" value="${String(d.horario_corte).slice(0,5)}"><button class="soft" onclick="saveDay(${i})">Salvar</button></div>`}).join('');$('#exceptionsList').innerHTML=exceptions.map(x=>`<div class="exception-row"><span>${fmt(x.data_original)}</span><span>${x.cancelada?'Cancelada':'→ '+fmt(x.nova_data)}</span></div>`).join('')}
window.saveDay=async i=>{let {error}=await sb.rpc('gerente_salvar_dia',{p_dia:i,p_ativo:$(`#day${i}`).checked,p_corte:$(`#cut${i}`).value,p_antes:1});if(error)return err(error);toast('Dia atualizado');await loadDelivery()};$('#saveException').onclick=async()=>{let {error}=await sb.rpc('gerente_salvar_excecao',{p_original:$('#exceptionOriginal').value||null,p_nova:$('#exceptionNew').value||null,p_cancelada:$('#exceptionCancel').checked});if(error)return err(error);toast('Exceção salva');await loadDelivery()};
async function loadDevices(){let {data}=await sb.rpc('gerente_listar_computadores');$('#devicesList').innerHTML=(data||[]).map(d=>`<div class="device-row"><span>${esc(d.nome)}</span><small>${d.ativo?'Ativo':'Removido'}</small>${d.ativo?`<button class="danger" onclick="removeDevice('${d.auth_uid}')">Remover</button>`:''}</div>`).join('')};window.removeDevice=async uid=>{if(!confirm('Remover este computador?'))return;let {error}=await sb.rpc('gerente_remover_computador',{p_uid:uid});if(error)return err(error);await loadDevices()};$('#changePassword').onclick=async()=>{let {error}=await sb.rpc('gerente_trocar_senha',{p_nova:$('#newPassword').value});if(error)return err(error);$('#newPassword').value='';toast('Senha alterada')};$('#logoutBtn').onclick=async()=>{await sb.auth.signOut();location.reload()};
let channel=sb ? sb.channel('gerente-live').on('postgres_changes',{event:'*',schema:'public',table:'pedidos'},()=>{loadOrders();loadPreparation()}).on('postgres_changes',{event:'*',schema:'public',table:'mensagens'},()=>{loadChats();if(activeClient)loadMessages()}).on('postgres_changes',{event:'*',schema:'public',table:'produtos'},()=>loadProducts()).subscribe() : null;
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
if(sb) ensureAuth().catch(err);
