-- Produtos Gilçana Gerente V2.1 - Integração WhatsApp Cloud API
begin;

create table if not exists public.whatsapp_envios (
 id bigint generated by default as identity primary key,
 cliente_id bigint references public.clientes(id) on delete set null,
 pedido_id bigint references public.pedidos(id) on delete set null,
 tipo text not null,
 telefone text,
 status text not null default 'pendente',
 meta_message_id text,
 erro text,
 criado_em timestamptz not null default now(),
 enviado_em timestamptz
);
alter table public.whatsapp_envios enable row level security;

create or replace function public.gerente_marcar_pronto_envio(p_id bigint)
returns void language plpgsql security definer set search_path='' as $$
begin
 if not public.sou_gerente() then raise exception 'Não autorizado.'; end if;
 update public.pedidos set status='pronto_envio' where id=p_id and status='confirmado';
 if not found then raise exception 'Pedido não encontrado ou não está em preparação.'; end if;
end $$;
revoke all on function public.gerente_marcar_pronto_envio(bigint) from public,anon;
grant execute on function public.gerente_marcar_pronto_envio(bigint) to authenticated;

create or replace function public.gerente_whatsapp_historico(p_limite integer default 50)
returns jsonb language plpgsql security definer set search_path='' stable as $$
declare j jsonb;
begin
 if not public.sou_gerente() then raise exception 'Não autorizado.'; end if;
 select coalesce(jsonb_agg(to_jsonb(x) order by x.criado_em desc),'[]'::jsonb) into j
 from (
   select w.id,w.tipo,w.telefone,w.status,w.meta_message_id,w.erro,w.criado_em,w.enviado_em,
          coalesce(c.nome_empresa,c.nome_cliente) cliente,p.numero pedido_numero
   from public.whatsapp_envios w
   left join public.clientes c on c.id=w.cliente_id
   left join public.pedidos p on p.id=w.pedido_id
   order by w.criado_em desc limit greatest(1,least(coalesce(p_limite,50),200))
 ) x;
 return j;
end $$;
revoke all on function public.gerente_whatsapp_historico(integer) from public,anon;
grant execute on function public.gerente_whatsapp_historico(integer) to authenticated;

commit;
